### PR TITLE
Re-enable livechat module:

### PR DESCRIPTION
**Pull request by luciofm**
- Rename LiveChatAPI to LiveChatClient
- Revert Callbacks to interfaces
- Rename some LiveChat listeners do Callbacks
- Moved some classes to an internal package
- removed old LiveChat tests - need to reimplement them based on WebsocketImplTest

### CODE REVIEW

**Comment by sacOO7** [comment]
Yes, will take a look at it :+1: .

**Comment by sacOO7** [comment]
What should be hierarchy of integrating modules? I'm gonna push some updates to this PR. I think it will be better to merge top PRs first into base and then into develop

**Comment by luciofm** [comment]
@sacOO7 create a new branch from this one with your changes, and open a PR on top of livechat branch, or we merge everything to develop, and a new PR on top of develop

**Comment by sacOO7** [comment]
@luciofm I think it's better to create new branch, I will merge it's changes into LiveChat . Let's fix everything one by one and then into develop.

**Pull request merged**
