### PR TITLE
Coding style and visibility of internal constants

### PR DESCRIPTION
**Pull request by luciofm**
Apply our coding style to the project (Core SDK only), change visibility of variables and constants

### CODE REVIEW

**Comment by luciofm** [comment]
Coding style: https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/CODING_STYLE.md
Coding style config: https://github.com/RocketChat/java-code-styles

**Comment by rafaelks** [comment]
Looking good, thanks @luciofm!

Please, review it and merge @sacOO7!

**Review by rafaelks — APPROVED** [review]

**Comment by sacOO7** [comment]
Hey @luciofm , I think you have applied changes to LiveChat SDK also, all of the files have changed.
I think PR is too big also for me to analyze, it took more than a hour
About styling, there are certain things we can discuss
1. toString method : In this method, string is supposed to be readable, your styler is converting it into one big line which is not readable and I have to scroll a lot to find the item.
2. enum : It has also been changed to single line, instead of one by one readable format, and its put at the bottom of the file ( I'm not sure, but I think it will be more useful if we can put it on the top)
3. Changing arrayList to List : This shouldn't affect the program, but you should give a thought on this.

**Comment by luciofm** [comment]
Thanks @sacOO7, I'm fixing the `toString` and `enum` issues...

About the `ArrayList`/`List` only the implementation should care about which type of List are using, callers should always use the `interface`, that way if you need to change from `ArrayList` to `LinkedList`, for example, the caller doesn't need to change... Some times it is even useful to return, or accept as parameter, a `Collection`

**Review by sacOO7 — APPROVED** [review]
Great work :), will integrate and build it

**Comment by sacOO7** [comment]
Please add gradle folder to the .gitignore

**Pull request merged**
